# See: https://github.com/troessner/reek#configuration-options

detectors:
  Attribute:
    enabled: false
  DuplicateMethodCall:
    exclude:
      - "self.test"
  TooManyStatements:
    exclude:
      - "self.test"
  UncommunicativeVariableName:
    exclude:
      - "self.test"
  UtilityFunction:
    exclude:
      - "/Say#(do_)?say.*/"

exclude_paths:
  - script
  - test/**/*
