# Load Rubocop plugins.
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance

inherit_gem:
  gemwork: lib/rubocop/.rubocop-gems.yml

AllCops:
  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 100

Minitest/MultipleAssertions:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Naming/BlockParameterName:
  Exclude:
    - say.gemspec

Style/FormatStringToken:
  # Prefer "%{my_template_value}" # <- Same style as is used in YAML
  # Over:
  # - "%<my_template_value>"
  # - "%s"
  EnforcedStyle: template
